/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package_Accounting;

/**
 *
 * @author marionne pascual
 */
import dao.BalanceSheetDA;
import dao.BalanceSheetDA.AccountBalance;
import javax.swing.table.DefaultTableModel;
import java.util.*;

public class BalanceSheet extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BalanceSheet.class.getName());

    /**
     * Creates new form BalanceSheet
     */
    public BalanceSheet() {
        initComponents();
        loadBalanceSheetData();
    }
    
    public void loadBalanceSheetData() {
        txtCompany_Name.setText(BalanceSheetDA.getCompanyName());
        Map<String, List<AccountBalance>> data = BalanceSheetDA.getBalanceSheetData();

        loadTable(tblCurrentAssets, data.get("CurrentAsset"));
        loadTable(tblNoncurrentAssets, data.get("NoncurrentAsset"));
        loadTable(tblLiabilities, data.get("Liabilities"));
        loadTable(tblEquity, data.get("Equity"));

        double totalCurrent = sumBalances(data.get("CurrentAsset"));
        double totalNoncurrent = sumBalances(data.get("NoncurrentAsset"));
        double totalAssets = totalCurrent + totalNoncurrent;
        double totalLiabilities = sumBalances(data.get("Liabilities"));
        double totalEquity = sumBalances(data.get("Equity"));

        txtTotalAssets.setText(String.format("%.2f", totalAssets));
        txtTotalLiabilities.setText(String.format("%.2f", totalLiabilities));
        txtTotalEquity.setText(String.format("%.2f", totalEquity));
    }

    public void loadTable(javax.swing.JTable table, List<AccountBalance> list) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (AccountBalance acc : list) {
            model.addRow(new Object[]{acc.accountTitle, acc.balance});
        }
    }

    public double sumBalances(List<AccountBalance> list) {
        return list.stream().mapToDouble(a -> a.balance).sum();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCompany_Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurrentAssets = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNoncurrentAssets = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLiabilities = new javax.swing.JTable();
        txtTotalAssets = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEquity = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotalLiabilities = new javax.swing.JTextField();
        txtTotalEquity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 226, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(191, 218, 232));

        txtCompany_Name.setEditable(false);
        txtCompany_Name.setBackground(new java.awt.Color(191, 218, 232));
        txtCompany_Name.setFont(new java.awt.Font("Rockwell", 1, 84)); // NOI18N
        txtCompany_Name.setForeground(new java.awt.Color(122, 133, 193));
        txtCompany_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCompany_Name.setText("Company Name");
        txtCompany_Name.setToolTipText("");
        txtCompany_Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCompany_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCompany_Name.setFocusable(false);
        txtCompany_Name.setOpaque(false);
        txtCompany_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompany_NameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 133, 193));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Balance Sheet");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCompany_Name)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtCompany_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1541, -1));

        tblCurrentAssets.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblCurrentAssets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Current Assets", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCurrentAssets);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 269, 380, 115));

        tblNoncurrentAssets.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblNoncurrentAssets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Noncurrent Asset", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblNoncurrentAssets);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 402, 380, 114));

        tblLiabilities.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblLiabilities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Liabilities", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblLiabilities);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 270, 380, 114));

        txtTotalAssets.setEditable(false);
        txtTotalAssets.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jPanel1.add(txtTotalAssets, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 522, 103, 37));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 133, 193));
        jLabel2.setText("Assets");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 234, 106, -1));

        tblEquity.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblEquity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equity", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblEquity);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 270, 380, 114));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 133, 193));
        jLabel3.setText("Equity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 235, 153, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 133, 193));
        jLabel4.setText("Liabilities");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 235, 153, -1));

        txtTotalLiabilities.setEditable(false);
        txtTotalLiabilities.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jPanel1.add(txtTotalLiabilities, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 390, 103, 37));

        txtTotalEquity.setEditable(false);
        txtTotalEquity.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jPanel1.add(txtTotalEquity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1324, 390, 103, 37));

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel5.setText("Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 397, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel6.setText("Total:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 529, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel7.setText("Total:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1271, 397, -1, -1));

        btnDone.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        jPanel1.add(btnDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1355, 529, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCompany_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompany_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompany_NameActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BalanceSheet().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblCurrentAssets;
    private javax.swing.JTable tblEquity;
    private javax.swing.JTable tblLiabilities;
    private javax.swing.JTable tblNoncurrentAssets;
    private javax.swing.JTextField txtCompany_Name;
    private javax.swing.JTextField txtTotalAssets;
    private javax.swing.JTextField txtTotalEquity;
    private javax.swing.JTextField txtTotalLiabilities;
    // End of variables declaration//GEN-END:variables
}
