/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package_Accounting;

/**
 *
 * @author marionne pascual
 */
import dao.IncomeStatementDB;
import dao.IncomeStatementDB.AccountBalance;
import javax.swing.table.DefaultTableModel;
import java.util.*;

public class IncomeStatement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IncomeStatement.class.getName());
    public static double latestNetIncome = 0;
    /**
     * Creates new form IncomeStatement
     */
    public IncomeStatement() {
        initComponents();
        loadIncomeStatement();
    }
    
    public  void loadIncomeStatement() {
        txtCompany_Name.setText(IncomeStatementDB.getCompanyName());
        Map<String, List<AccountBalance>> data = IncomeStatementDB.getIncomeStatementData();

        loadTable(tblIncome, data.get("Income"));
        loadTable(tblExpense, data.get("Expense"));

        double totalIncome = sumBalances(data.get("Income"));
        double totalCOGS = sumBalances(data.get("COGS"));
        double totalExpense = sumBalances(data.get("Expense"));

        DefaultTableModel model = (DefaultTableModel) tblIncome.getModel();
        
        if (totalCOGS > 0) {
            model.addRow(new Object[]{"(less) Cost of Goods Sold", String.format("%.2f", totalCOGS)});
            double grossProfit = totalIncome - totalCOGS;
            txtTotalIncome.setText(String.format("%.2f", grossProfit));
        }else
            txtTotalIncome.setText(String.format("%.2f", totalIncome));

        double netIncome;
        if (totalCOGS > 0)
            netIncome = (totalIncome - totalCOGS) - totalExpense;
        else
            netIncome = totalIncome - totalExpense;

        txtTotalExpense.setText(String.format("%.2f", totalExpense));

        if (netIncome > 0)
            txtNetIncome.setText("Net Income: " + String.format("%.2f", netIncome));
        else if (netIncome < 0)
            txtNetIncome.setText("(less) Net Loss: " + String.format("%.2f", Math.abs(netIncome)));
        else
            txtNetIncome.setText("");


        IncomeStatementDB.netIncome = netIncome;
    }

    public  void loadTable(javax.swing.JTable table, List<AccountBalance> list) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (AccountBalance acc : list) {
            model.addRow(new Object[]{acc.accountTitle, acc.balance});
        }
    }

    public double sumBalances(List<AccountBalance> list) {
        return list.stream().mapToDouble(a -> a.balance).sum();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtCompany_Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIncome = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblExpense = new javax.swing.JTable();
        txtTotalIncome = new javax.swing.JTextField();
        txtTotalExpense = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        txtNetIncome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 226, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(191, 218, 232));

        txtCompany_Name.setEditable(false);
        txtCompany_Name.setBackground(new java.awt.Color(191, 218, 232));
        txtCompany_Name.setFont(new java.awt.Font("Rockwell", 1, 84)); // NOI18N
        txtCompany_Name.setForeground(new java.awt.Color(122, 133, 193));
        txtCompany_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCompany_Name.setText("Company Name");
        txtCompany_Name.setToolTipText("");
        txtCompany_Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCompany_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCompany_Name.setFocusable(false);
        txtCompany_Name.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 133, 193));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Income Statement");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCompany_Name)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtCompany_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1541, -1));

        tblIncome.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblIncome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Income", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblIncome);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, 195));

        tblExpense.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblExpense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Expense", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblExpense);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, 195));

        txtTotalIncome.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtTotalIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalIncomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 110, 35));

        txtTotalExpense.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jPanel1.add(txtTotalExpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 700, 110, 35));

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 133, 193));
        jLabel4.setText("Expense");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 452, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(122, 133, 193));
        jLabel5.setText("Income");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 452, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel6.setText("Total:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 710, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel7.setText("Gross Profit:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));

        btnDone.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        jPanel1.add(btnDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 760, -1, -1));

        txtNetIncome.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jPanel1.add(txtNetIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 750, 170, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_btnDoneActionPerformed

    private void txtTotalIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalIncomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IncomeStatement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblExpense;
    private javax.swing.JTable tblIncome;
    private javax.swing.JTextField txtCompany_Name;
    private javax.swing.JTextField txtNetIncome;
    private javax.swing.JTextField txtTotalExpense;
    private javax.swing.JTextField txtTotalIncome;
    // End of variables declaration//GEN-END:variables
}
