/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package_Accounting;

import dao.JournalDA;
import javax.swing.*;
import model.User;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.sql.*;
import java.util.List;
/**
 *
 * @author marionne pascual
 */
public class Journal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Journal.class.getName());
    private int currentJournalId = 0;
     private DefaultTableModel model;

    /**
     * Creates new form Journal
     */
    public Journal(int journalId) {
        initComponents();
        this.currentJournalId = journalId;
        JOptionPane.showMessageDialog(null, "Journal window opened with ID: " + currentJournalId);
        btnConfirm.setEnabled(false);
        
        String companyName = JournalDA.getCompanyName();
        
        if (companyName == null || companyName.trim().isEmpty()) {
            companyName = JOptionPane.showInputDialog(this, "Enter Company Name:");
            if (companyName != null && !companyName.trim().isEmpty()) {
                JournalDA.saveCompanyName(companyName);
            } else {
                companyName = "Unnamed Company";
            }
        }

        txtCompany_Name.setText(companyName);
        
        model = (DefaultTableModel) journalView.getModel();
        loadJournalData();
    }
    
    public Journal() {
        initComponents();
        User user = new User();
        
        this.currentJournalId = 0;
        btnConfirm.setEnabled(false);
        String companyName = user.loadCompanyName(); // Try to read saved name

    if (companyName == null || companyName.isEmpty()) {
        companyName = JOptionPane.showInputDialog(null, "Enter Company Name:");
        if (companyName != null && !companyName.trim().isEmpty()) {
            user.saveCompanyName(companyName);
        } else {
            companyName = "Unnamed Company";
        }
    }
        
        txtCompany_Name.setText(companyName);
        model = (DefaultTableModel) journalView.getModel();
        loadJournalData();

        
    }
    
     private void loadJournalData() {
        model.setRowCount(0); // clear table
        List<Object[]> entries = JournalDA.getAllJournalEntries();
        for (Object[] row : entries) {
            model.addRow(row);
        }
    }
    
    public void clear(){
        txtAcc_Title.setText("");
        txtDebit.setText("");
        txtCredit.setText("");
        btnConfirm.setEnabled(false);
    }
    
    public void validateFields(){
        String accTitle = txtAcc_Title.getText();
        int deb = Integer.parseInt(txtDebit.getText());
        int cred = Integer.parseInt(txtCredit.getText());
        if(!"".equals(accTitle) && deb >= 0 && cred >= 0)
            btnConfirm.setEnabled(true);
        else
            btnConfirm.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAcc_Title = new javax.swing.JTextField();
        txtDebit = new javax.swing.JTextField();
        txtCredit = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtCompany_Name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        journalView = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(210, 226, 235));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(191, 218, 232));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 133, 193));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Account Title");

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 133, 193));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Debit");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 133, 193));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Credit");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 133, 193));
        jLabel4.setText("General Journal");

        txtAcc_Title.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtAcc_Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcc_TitleActionPerformed(evt);
            }
        });
        txtAcc_Title.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAcc_TitleKeyReleased(evt);
            }
        });

        txtDebit.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDebitActionPerformed(evt);
            }
        });
        txtDebit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDebitKeyReleased(evt);
            }
        });

        txtCredit.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditActionPerformed(evt);
            }
        });
        txtCredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCreditKeyReleased(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnCancel.setText("Done");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtAcc_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addGap(89, 89, 89)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAcc_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnClear)
                    .addComponent(btnDelete))
                .addGap(47, 47, 47)
                .addComponent(btnCancel)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 830));

        txtCompany_Name.setEditable(false);
        txtCompany_Name.setBackground(new java.awt.Color(210, 226, 235));
        txtCompany_Name.setFont(new java.awt.Font("Rockwell", 1, 84)); // NOI18N
        txtCompany_Name.setForeground(new java.awt.Color(122, 133, 193));
        txtCompany_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCompany_Name.setText("Company Name");
        txtCompany_Name.setToolTipText("");
        txtCompany_Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCompany_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCompany_Name.setFocusable(false);
        txtCompany_Name.setOpaque(false);
        txtCompany_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompany_NameActionPerformed(evt);
            }
        });
        jPanel4.add(txtCompany_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 40, 920, -1));

        journalView.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        journalView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Journal Id", "Account Title", "Debit", "Credit"
            }
        ));
        jScrollPane2.setViewportView(journalView);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 920, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCreditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtCreditKeyReleased

    private void txtCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditActionPerformed

    private void txtDebitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDebitKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtDebitKeyReleased

    private void txtDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDebitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDebitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        try{
            if (currentJournalId == 0) {
                JOptionPane.showMessageDialog(null, "No active journal. Please create one first.");
                return;
            }
            User user = new User();
            user.setAccountTitle(txtAcc_Title.getText());
            user.setDebit(Integer.parseInt(txtDebit.getText()));
            user.setCredit(Integer.parseInt(txtCredit.getText()));
            
            currentJournalId = JournalDA.addJournalEntry(currentJournalId, user);

            clear();
            loadJournalData();
            txtAcc_Title.requestFocus();
            /*boolean confirm = JournalDA.addJournalEntry(currentJournalId, user);
            if(confirm){
                clear();
                loadJournalData();
            }
            else{
                Menu men = new Menu();
                men.setVisible(true);
                this.dispose();
            }*/
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid input!");

        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtAcc_TitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcc_TitleKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtAcc_TitleKeyReleased

    private void txtAcc_TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcc_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcc_TitleActionPerformed

    private void txtCompany_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompany_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompany_NameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        JournalDA.deleteLastJournalEntry();
        loadJournalData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /*private void jScrollPane2Performed(java.awt.event.ActionEvent evt){
        JournalDA Journal = new JournalDA();
        try {
                    String accIdStr = JOptionPane.showInputDialog("Enter Account ID:");
                    String debitStr = JOptionPane.showInputDialog("Enter Debit amount:");
                    String creditStr = JOptionPane.showInputDialog("Enter Credit amount:");

                    int accountId = Integer.parseInt(accIdStr);
                    int debit = Integer.parseInt(debitStr);
                    int credit = Integer.parseInt(creditStr);

                    Journal.addJournalEntry(accountId, debit, credit);
                    JOptionPane.showMessageDialog(null, "Journal Entry Added!");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Invalid input!");
                }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Journal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable journalView;
    private javax.swing.JTextField txtAcc_Title;
    private javax.swing.JTextField txtCompany_Name;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtDebit;
    // End of variables declaration//GEN-END:variables
}
