/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package_Accounting;

/**
 *
 * @author marionne pascual
 */

import dao.LedgerDA;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Map;
import java.util.List;
import java.util.LinkedHashMap;
import java.util.ArrayList;

public class LedgerView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LedgerView.class.getName());

    /**
     * Creates new form LedgerView
     */
    public LedgerView() {
        initComponents();
        loadLedgerData();
        
    }
    public void loadLedgerData() {
        txtCompany_Name.setText(LedgerDA.getCompanyName());
     List<LedgerDA.LedgerEntry> ledgerList = LedgerDA.getLedgerData();

    
    JTextField[] titleFields = {
        Account_Titles, Account_Titles1, Account_Titles2, Account_Titles3,
        Account_Titles4, Account_Titles5, Account_Titles6, Account_Titles7,
        Account_Titles8, Account_Titles9, Account_Titles10, Account_Titles11,
        Account_Titles12, Account_Titles13, Account_Titles14, Account_Titles15,
        Account_Titles16, Account_Titles17
    };

    JTextField[] totalFields = {
        Total, Total1, Total2, Total3, Total4, Total5, Total6, Total7,
        Total8, Total9, Total10, Total11, Total12, Total13, Total14,
        Total15, Total16, Total17
    };

    JTable[] tables = {
        tblContents1, tblContents2, tblContents3, tblContents4,
        tblContents5, tblContents6, tblContents7, tblContents8,
        tblContents9, tblContents10, tblContents11, tblContents12,
        tblContents13, tblContents14, tblContents15, tblContents16,
        tblContents17, tblContents18
    };

   
    for (int i = 0; i < ledgerList.size() && i < tables.length; i++) {
        LedgerDA.LedgerEntry entry = ledgerList.get(i);
        titleFields[i].setText(entry.accountTitle);

        
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Debit", "Credit"}, 0);
        for (double[] trans : entry.transactions) {
            model.addRow(new Object[]{trans[0] == 0 ? "" : trans[0], trans[1] == 0 ? "" :trans[1]});
        }
        tables[i].setModel(model);

        
        double diff = entry.totalDebit - entry.totalCredit;
        if (diff > 0) {
            totalFields[i].setText("Debit: " + diff);
        } else if (diff < 0) {
            totalFields[i].setText("Credit: " + Math.abs(diff));
        } else {
            totalFields[i].setText("Balanced");
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCompany_Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContents1 = new javax.swing.JTable();
        Account_Titles = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContents2 = new javax.swing.JTable();
        Account_Titles1 = new javax.swing.JTextField();
        Total1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblContents3 = new javax.swing.JTable();
        Account_Titles2 = new javax.swing.JTextField();
        Total2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblContents4 = new javax.swing.JTable();
        Account_Titles3 = new javax.swing.JTextField();
        Total3 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblContents5 = new javax.swing.JTable();
        Account_Titles4 = new javax.swing.JTextField();
        Total4 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblContents6 = new javax.swing.JTable();
        Account_Titles5 = new javax.swing.JTextField();
        Total5 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblContents7 = new javax.swing.JTable();
        Account_Titles6 = new javax.swing.JTextField();
        Total6 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblContents8 = new javax.swing.JTable();
        Account_Titles7 = new javax.swing.JTextField();
        Total7 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblContents9 = new javax.swing.JTable();
        Account_Titles8 = new javax.swing.JTextField();
        Total8 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblContents10 = new javax.swing.JTable();
        Account_Titles9 = new javax.swing.JTextField();
        Total9 = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblContents11 = new javax.swing.JTable();
        Account_Titles10 = new javax.swing.JTextField();
        Total10 = new javax.swing.JTextField();
        jScrollPanel12 = new javax.swing.JScrollPane();
        tblContents12 = new javax.swing.JTable();
        Account_Titles11 = new javax.swing.JTextField();
        Total11 = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblContents13 = new javax.swing.JTable();
        Account_Titles12 = new javax.swing.JTextField();
        Total12 = new javax.swing.JTextField();
        jScrollPane14 = new javax.swing.JScrollPane();
        tblContents14 = new javax.swing.JTable();
        Account_Titles13 = new javax.swing.JTextField();
        Total13 = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        tblContents15 = new javax.swing.JTable();
        Account_Titles14 = new javax.swing.JTextField();
        Total14 = new javax.swing.JTextField();
        jScrollPane16 = new javax.swing.JScrollPane();
        tblContents16 = new javax.swing.JTable();
        Account_Titles15 = new javax.swing.JTextField();
        Total15 = new javax.swing.JTextField();
        jScrollPane17 = new javax.swing.JScrollPane();
        tblContents17 = new javax.swing.JTable();
        Account_Titles16 = new javax.swing.JTextField();
        Total16 = new javax.swing.JTextField();
        jScrollPane18 = new javax.swing.JScrollPane();
        tblContents18 = new javax.swing.JTable();
        Account_Titles17 = new javax.swing.JTextField();
        Total17 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1451, 830));

        jPanel1.setBackground(new java.awt.Color(210, 226, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(1451, 830));

        jPanel2.setBackground(new java.awt.Color(191, 218, 232));

        txtCompany_Name.setEditable(false);
        txtCompany_Name.setBackground(new java.awt.Color(191, 218, 232));
        txtCompany_Name.setFont(new java.awt.Font("Rockwell", 1, 84)); // NOI18N
        txtCompany_Name.setForeground(new java.awt.Color(122, 133, 193));
        txtCompany_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCompany_Name.setText("Company Name");
        txtCompany_Name.setToolTipText("");
        txtCompany_Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCompany_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCompany_Name.setFocusable(false);
        txtCompany_Name.setOpaque(false);
        txtCompany_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompany_NameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 133, 193));
        jLabel4.setText("Genral Ledger");

        btnDone.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCompany_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(556, 556, 556)
                        .addComponent(btnDone))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtCompany_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDone))
        );

        tblContents1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane1.setViewportView(tblContents1);

        Account_Titles.setEditable(false);
        Account_Titles.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles.setText("Account Title");
        Account_Titles.setRequestFocusEnabled(false);
        Account_Titles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_TitlesActionPerformed(evt);
            }
        });

        Total.setEditable(false);
        Total.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(122, 133, 193));
        Total.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total.setText("Total(debit/credit): ");
        Total.setRequestFocusEnabled(false);
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        tblContents2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane2.setViewportView(tblContents2);

        Account_Titles1.setEditable(false);
        Account_Titles1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles1.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles1.setText("Account Title");
        Account_Titles1.setRequestFocusEnabled(false);
        Account_Titles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles1ActionPerformed(evt);
            }
        });

        Total1.setEditable(false);
        Total1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total1.setForeground(new java.awt.Color(122, 133, 193));
        Total1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total1.setText("Total(debit/credit): ");
        Total1.setRequestFocusEnabled(false);
        Total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total1ActionPerformed(evt);
            }
        });

        tblContents3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane3.setViewportView(tblContents3);

        Account_Titles2.setEditable(false);
        Account_Titles2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles2.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles2.setText("Account Title");
        Account_Titles2.setRequestFocusEnabled(false);
        Account_Titles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles2ActionPerformed(evt);
            }
        });

        Total2.setEditable(false);
        Total2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total2.setForeground(new java.awt.Color(122, 133, 193));
        Total2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total2.setText("Total(debit/credit): ");
        Total2.setRequestFocusEnabled(false);
        Total2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total2ActionPerformed(evt);
            }
        });

        tblContents4.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane4.setViewportView(tblContents4);

        Account_Titles3.setEditable(false);
        Account_Titles3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles3.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles3.setText("Account Title");
        Account_Titles3.setRequestFocusEnabled(false);
        Account_Titles3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles3ActionPerformed(evt);
            }
        });

        Total3.setEditable(false);
        Total3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total3.setForeground(new java.awt.Color(122, 133, 193));
        Total3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total3.setText("Total(debit/credit): ");
        Total3.setRequestFocusEnabled(false);
        Total3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total3ActionPerformed(evt);
            }
        });

        tblContents5.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane5.setViewportView(tblContents5);

        Account_Titles4.setEditable(false);
        Account_Titles4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles4.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles4.setText("Account Title");
        Account_Titles4.setRequestFocusEnabled(false);
        Account_Titles4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles4ActionPerformed(evt);
            }
        });

        Total4.setEditable(false);
        Total4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total4.setForeground(new java.awt.Color(122, 133, 193));
        Total4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total4.setText("Total(debit/credit): ");
        Total4.setRequestFocusEnabled(false);
        Total4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total4ActionPerformed(evt);
            }
        });

        tblContents6.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane6.setViewportView(tblContents6);

        Account_Titles5.setEditable(false);
        Account_Titles5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles5.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles5.setText("Account Title");
        Account_Titles5.setRequestFocusEnabled(false);
        Account_Titles5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles5ActionPerformed(evt);
            }
        });

        Total5.setEditable(false);
        Total5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total5.setForeground(new java.awt.Color(122, 133, 193));
        Total5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total5.setText("Total(debit/credit): ");
        Total5.setRequestFocusEnabled(false);
        Total5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total5ActionPerformed(evt);
            }
        });

        tblContents7.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane7.setViewportView(tblContents7);

        Account_Titles6.setEditable(false);
        Account_Titles6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles6.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles6.setText("Account Title");
        Account_Titles6.setRequestFocusEnabled(false);
        Account_Titles6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles6ActionPerformed(evt);
            }
        });

        Total6.setEditable(false);
        Total6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total6.setForeground(new java.awt.Color(122, 133, 193));
        Total6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total6.setText("Total(debit/credit): ");
        Total6.setRequestFocusEnabled(false);
        Total6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total6ActionPerformed(evt);
            }
        });

        tblContents8.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane8.setViewportView(tblContents8);

        Account_Titles7.setEditable(false);
        Account_Titles7.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles7.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles7.setText("Account Title");
        Account_Titles7.setRequestFocusEnabled(false);
        Account_Titles7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles7ActionPerformed(evt);
            }
        });

        Total7.setEditable(false);
        Total7.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total7.setForeground(new java.awt.Color(122, 133, 193));
        Total7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total7.setText("Total(debit/credit): ");
        Total7.setRequestFocusEnabled(false);
        Total7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total7ActionPerformed(evt);
            }
        });

        tblContents9.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane9.setViewportView(tblContents9);

        Account_Titles8.setEditable(false);
        Account_Titles8.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles8.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles8.setText("Account Title");
        Account_Titles8.setRequestFocusEnabled(false);
        Account_Titles8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles8ActionPerformed(evt);
            }
        });

        Total8.setEditable(false);
        Total8.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total8.setForeground(new java.awt.Color(122, 133, 193));
        Total8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total8.setText("Total(debit/credit): ");
        Total8.setRequestFocusEnabled(false);
        Total8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total8ActionPerformed(evt);
            }
        });

        tblContents10.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane10.setViewportView(tblContents10);

        Account_Titles9.setEditable(false);
        Account_Titles9.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles9.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles9.setText("Account Title");
        Account_Titles9.setRequestFocusEnabled(false);
        Account_Titles9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles9ActionPerformed(evt);
            }
        });

        Total9.setEditable(false);
        Total9.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total9.setForeground(new java.awt.Color(122, 133, 193));
        Total9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total9.setText("Total(debit/credit): ");
        Total9.setRequestFocusEnabled(false);
        Total9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total9ActionPerformed(evt);
            }
        });

        tblContents11.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane11.setViewportView(tblContents11);

        Account_Titles10.setEditable(false);
        Account_Titles10.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles10.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles10.setText("Account Title");
        Account_Titles10.setRequestFocusEnabled(false);
        Account_Titles10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles10ActionPerformed(evt);
            }
        });

        Total10.setEditable(false);
        Total10.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total10.setForeground(new java.awt.Color(122, 133, 193));
        Total10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total10.setText("Total(debit/credit): ");
        Total10.setRequestFocusEnabled(false);
        Total10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total10ActionPerformed(evt);
            }
        });

        tblContents12.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPanel12.setViewportView(tblContents12);

        Account_Titles11.setEditable(false);
        Account_Titles11.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles11.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles11.setText("Account Title");
        Account_Titles11.setRequestFocusEnabled(false);
        Account_Titles11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles11ActionPerformed(evt);
            }
        });

        Total11.setEditable(false);
        Total11.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total11.setForeground(new java.awt.Color(122, 133, 193));
        Total11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total11.setText("Total(debit/credit): ");
        Total11.setRequestFocusEnabled(false);
        Total11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total11ActionPerformed(evt);
            }
        });

        tblContents13.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane13.setViewportView(tblContents13);

        Account_Titles12.setEditable(false);
        Account_Titles12.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles12.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles12.setText("Account Title");
        Account_Titles12.setRequestFocusEnabled(false);
        Account_Titles12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles12ActionPerformed(evt);
            }
        });

        Total12.setEditable(false);
        Total12.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total12.setForeground(new java.awt.Color(122, 133, 193));
        Total12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total12.setText("Total(debit/credit): ");
        Total12.setRequestFocusEnabled(false);
        Total12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total12ActionPerformed(evt);
            }
        });

        tblContents14.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane14.setViewportView(tblContents14);

        Account_Titles13.setEditable(false);
        Account_Titles13.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles13.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles13.setText("Account Title");
        Account_Titles13.setRequestFocusEnabled(false);
        Account_Titles13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles13ActionPerformed(evt);
            }
        });

        Total13.setEditable(false);
        Total13.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total13.setForeground(new java.awt.Color(122, 133, 193));
        Total13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total13.setText("Total(debit/credit): ");
        Total13.setRequestFocusEnabled(false);
        Total13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total13ActionPerformed(evt);
            }
        });

        tblContents15.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane15.setViewportView(tblContents15);

        Account_Titles14.setEditable(false);
        Account_Titles14.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles14.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles14.setText("Account Title");
        Account_Titles14.setRequestFocusEnabled(false);
        Account_Titles14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles14ActionPerformed(evt);
            }
        });

        Total14.setEditable(false);
        Total14.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total14.setForeground(new java.awt.Color(122, 133, 193));
        Total14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total14.setText("Total(debit/credit): ");
        Total14.setRequestFocusEnabled(false);
        Total14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total14ActionPerformed(evt);
            }
        });

        tblContents16.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents16.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane16.setViewportView(tblContents16);

        Account_Titles15.setEditable(false);
        Account_Titles15.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles15.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles15.setText("Account Title");
        Account_Titles15.setRequestFocusEnabled(false);
        Account_Titles15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles15ActionPerformed(evt);
            }
        });

        Total15.setEditable(false);
        Total15.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total15.setForeground(new java.awt.Color(122, 133, 193));
        Total15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total15.setText("Total(debit/credit): ");
        Total15.setRequestFocusEnabled(false);
        Total15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total15ActionPerformed(evt);
            }
        });

        tblContents17.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents17.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane17.setViewportView(tblContents17);

        Account_Titles16.setEditable(false);
        Account_Titles16.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles16.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles16.setText("Account Title");
        Account_Titles16.setRequestFocusEnabled(false);
        Account_Titles16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles16ActionPerformed(evt);
            }
        });

        Total16.setEditable(false);
        Total16.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total16.setForeground(new java.awt.Color(122, 133, 193));
        Total16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total16.setText("Total(debit/credit): ");
        Total16.setRequestFocusEnabled(false);
        Total16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total16ActionPerformed(evt);
            }
        });

        tblContents18.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tblContents18.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debit", "Credit"
            }
        ));
        jScrollPane18.setViewportView(tblContents18);

        Account_Titles17.setEditable(false);
        Account_Titles17.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Account_Titles17.setForeground(new java.awt.Color(122, 133, 193));
        Account_Titles17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Account_Titles17.setText("Account Title");
        Account_Titles17.setRequestFocusEnabled(false);
        Account_Titles17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Account_Titles17ActionPerformed(evt);
            }
        });

        Total17.setEditable(false);
        Total17.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Total17.setForeground(new java.awt.Color(122, 133, 193));
        Total17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Total17.setText("Total(debit/credit): ");
        Total17.setRequestFocusEnabled(false);
        Total17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Account_Titles, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Account_Titles1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Account_Titles2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Account_Titles3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Total6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Account_Titles6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Total7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Total8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Total9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(Account_Titles7, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Account_Titles8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Account_Titles9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Total1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Total2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Total3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Total12, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Total13, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Account_Titles12, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Account_Titles13, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Account_Titles14, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(Account_Titles15, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Total14, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Total15, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Account_Titles10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Account_Titles11, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Total10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Total11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Account_Titles16, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Account_Titles17, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Total16, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Total17, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Account_Titles4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Account_Titles5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Account_Titles5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Account_Titles4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Account_Titles10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Account_Titles11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Account_Titles9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Account_Titles8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Account_Titles7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Account_Titles6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Total10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Total11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Total7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Total8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Total9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Total6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Account_Titles3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Account_Titles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Account_Titles1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Account_Titles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Account_Titles15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account_Titles14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account_Titles12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account_Titles13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account_Titles16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account_Titles17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(266, 266, 266))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCompany_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompany_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompany_NameActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void Total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total1ActionPerformed

    private void Total2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total2ActionPerformed

    private void Total3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total3ActionPerformed

    private void Total6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total6ActionPerformed

    private void Total7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total7ActionPerformed

    private void Total8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total8ActionPerformed

    private void Total9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total9ActionPerformed

    private void Total10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total10ActionPerformed

    private void Total11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total11ActionPerformed

    private void Total4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total4ActionPerformed

    private void Total5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total5ActionPerformed

    private void Total12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total12ActionPerformed

    private void Total13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total13ActionPerformed

    private void Total14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total14ActionPerformed

    private void Total15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total15ActionPerformed

    private void Total16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total16ActionPerformed

    private void Total17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total17ActionPerformed

    private void Account_TitlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_TitlesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_TitlesActionPerformed

    private void Account_Titles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles1ActionPerformed

    private void Account_Titles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles2ActionPerformed

    private void Account_Titles3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles3ActionPerformed

    private void Account_Titles4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles4ActionPerformed

    private void Account_Titles5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles5ActionPerformed

    private void Account_Titles6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles6ActionPerformed

    private void Account_Titles7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles7ActionPerformed

    private void Account_Titles8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles8ActionPerformed

    private void Account_Titles9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles9ActionPerformed

    private void Account_Titles12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles12ActionPerformed

    private void Account_Titles13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles13ActionPerformed

    private void Account_Titles14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles14ActionPerformed

    private void Account_Titles15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles15ActionPerformed

    private void Account_Titles10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles10ActionPerformed

    private void Account_Titles16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles16ActionPerformed

    private void Account_Titles11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles11ActionPerformed

    private void Account_Titles17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Account_Titles17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Account_Titles17ActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu men = new Menu();
        men.setVisible(true);
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LedgerView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Account_Titles;
    private javax.swing.JTextField Account_Titles1;
    private javax.swing.JTextField Account_Titles10;
    private javax.swing.JTextField Account_Titles11;
    private javax.swing.JTextField Account_Titles12;
    private javax.swing.JTextField Account_Titles13;
    private javax.swing.JTextField Account_Titles14;
    private javax.swing.JTextField Account_Titles15;
    private javax.swing.JTextField Account_Titles16;
    private javax.swing.JTextField Account_Titles17;
    private javax.swing.JTextField Account_Titles2;
    private javax.swing.JTextField Account_Titles3;
    private javax.swing.JTextField Account_Titles4;
    private javax.swing.JTextField Account_Titles5;
    private javax.swing.JTextField Account_Titles6;
    private javax.swing.JTextField Account_Titles7;
    private javax.swing.JTextField Account_Titles8;
    private javax.swing.JTextField Account_Titles9;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField Total1;
    private javax.swing.JTextField Total10;
    private javax.swing.JTextField Total11;
    private javax.swing.JTextField Total12;
    private javax.swing.JTextField Total13;
    private javax.swing.JTextField Total14;
    private javax.swing.JTextField Total15;
    private javax.swing.JTextField Total16;
    private javax.swing.JTextField Total17;
    private javax.swing.JTextField Total2;
    private javax.swing.JTextField Total3;
    private javax.swing.JTextField Total4;
    private javax.swing.JTextField Total5;
    private javax.swing.JTextField Total6;
    private javax.swing.JTextField Total7;
    private javax.swing.JTextField Total8;
    private javax.swing.JTextField Total9;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPanel12;
    private javax.swing.JTable tblContents1;
    private javax.swing.JTable tblContents10;
    private javax.swing.JTable tblContents11;
    private javax.swing.JTable tblContents12;
    private javax.swing.JTable tblContents13;
    private javax.swing.JTable tblContents14;
    private javax.swing.JTable tblContents15;
    private javax.swing.JTable tblContents16;
    private javax.swing.JTable tblContents17;
    private javax.swing.JTable tblContents18;
    private javax.swing.JTable tblContents2;
    private javax.swing.JTable tblContents3;
    private javax.swing.JTable tblContents4;
    private javax.swing.JTable tblContents5;
    private javax.swing.JTable tblContents6;
    private javax.swing.JTable tblContents7;
    private javax.swing.JTable tblContents8;
    private javax.swing.JTable tblContents9;
    private javax.swing.JTextField txtCompany_Name;
    // End of variables declaration//GEN-END:variables
}
