/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package_Accounting;

import javax.swing.JOptionPane;

/**
 *
 * @author marionne pascual
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnJournal = new javax.swing.JButton();
        btnLedger = new javax.swing.JButton();
        btnAdjusted = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        btnIncome = new javax.swing.JButton();
        btnUnadjusted = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 226, 235));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnJournal.setBackground(new java.awt.Color(210, 226, 235));
        btnJournal.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnJournal.setForeground(new java.awt.Color(122, 133, 193));
        btnJournal.setText("Journal");
        btnJournal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJournalActionPerformed(evt);
            }
        });

        btnLedger.setBackground(new java.awt.Color(210, 226, 235));
        btnLedger.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnLedger.setForeground(new java.awt.Color(122, 133, 193));
        btnLedger.setText("Ledger");
        btnLedger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLedgerActionPerformed(evt);
            }
        });

        btnAdjusted.setBackground(new java.awt.Color(210, 226, 235));
        btnAdjusted.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        btnAdjusted.setForeground(new java.awt.Color(122, 133, 193));
        btnAdjusted.setText("Adjusted Trial Balance");
        btnAdjusted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjustedActionPerformed(evt);
            }
        });

        btnBalance.setBackground(new java.awt.Color(210, 226, 235));
        btnBalance.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnBalance.setForeground(new java.awt.Color(122, 133, 193));
        btnBalance.setText("Balance Sheet");
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });

        btnIncome.setBackground(new java.awt.Color(210, 226, 235));
        btnIncome.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnIncome.setForeground(new java.awt.Color(122, 133, 193));
        btnIncome.setText("Income Statment");
        btnIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncomeActionPerformed(evt);
            }
        });

        btnUnadjusted.setBackground(new java.awt.Color(210, 226, 235));
        btnUnadjusted.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        btnUnadjusted.setForeground(new java.awt.Color(122, 133, 193));
        btnUnadjusted.setText("Unadjusted Trial Balance");
        btnUnadjusted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnadjustedActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(122, 133, 193));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdjusted, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUnadjusted))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnJournal, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLedger, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJournal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLedger, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUnadjusted, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnAdjusted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnExit))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, -1, -1));

        jLabel1.setBackground(new java.awt.Color(122, 133, 193));
        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 133, 193));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Accounting System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 58));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJournalActionPerformed
        // TODO add your handling code here:
        int newJournalId = dao.JournalDA.createNewJournal();
        
        JOptionPane.showMessageDialog(null, "New Journal created with ID: " + newJournalId);
        Journal jf = new Journal(newJournalId);
        jf.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btnJournalActionPerformed

    private void btnLedgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLedgerActionPerformed
        // TODO add your handling code here:
        LedgerView lv = new LedgerView();
        lv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLedgerActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUnadjustedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnadjustedActionPerformed
        // TODO add your handling code here:
        UnadjustedTB UTB = new UnadjustedTB();
        UTB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUnadjustedActionPerformed

    private void btnAdjustedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjustedActionPerformed
        // TODO add your handling code here:
        AdjustedTB ATB = new AdjustedTB();
        ATB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdjustedActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        // TODO add your handling code here:
        BalanceSheet BS = new BalanceSheet();
        BS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void btnIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncomeActionPerformed
        // TODO add your handling code here:
        IncomeStatement IS = new IncomeStatement();
        IS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIncomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjusted;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIncome;
    private javax.swing.JButton btnJournal;
    private javax.swing.JButton btnLedger;
    private javax.swing.JButton btnUnadjusted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
