/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package_Accounting;

/**
 *
 * @author marionne pascual
 */
import dao.UnadjustedTBDA;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class UnadjustedTB extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UnadjustedTB.class.getName());

    /**
     * Creates new form UnadjustedTB
     */
    public UnadjustedTB() {
        initComponents();
        loadTrialBalance();
    }
    
    public void loadTrialBalance() {
        btnDone.requestFocus();
        txtCompany_Name.setText(UnadjustedTBDA.getCompanyName());
        List<UnadjustedTBDA.AccountTotal> tbList = UnadjustedTBDA.getTrialBalance();

        DefaultTableModel model = new DefaultTableModel(new Object[]{"Account Title", "Debit", "Credit"}, 0);
        double totalDebit = 0;
        double totalCredit = 0;

        for (UnadjustedTBDA.AccountTotal acc : tbList) {
            double debit = 0, credit = 0;

            
            if (acc.debitTotal > acc.creditTotal) {
                debit = acc.debitTotal - acc.creditTotal;
                totalDebit += debit;
            } else if (acc.creditTotal > acc.debitTotal) {
                credit = acc.creditTotal - acc.debitTotal;
                totalCredit += credit;
            }

            model.addRow(new Object[]{acc.accountTitle, debit == 0 ? "" : debit, credit == 0 ? "" : credit});
        }
        DisplayInfo.setModel(model);
        txtTotalDebit.setText("" + totalDebit);
        txtTotalCredit.setText("" + totalCredit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCompany_Name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayInfo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTotalDebit = new javax.swing.JTextField();
        txtTotalCredit = new javax.swing.JTextField();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 226, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(191, 218, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 133, 193));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Unadjusted Trial Balance");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 147, 436, -1));

        txtCompany_Name.setEditable(false);
        txtCompany_Name.setBackground(new java.awt.Color(191, 218, 232));
        txtCompany_Name.setFont(new java.awt.Font("Rockwell", 1, 84)); // NOI18N
        txtCompany_Name.setForeground(new java.awt.Color(122, 133, 193));
        txtCompany_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCompany_Name.setText("Company Name");
        txtCompany_Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtCompany_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 27, 1540, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1541, -1));

        DisplayInfo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        DisplayInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Titles", "Debit", "Credit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DisplayInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(DisplayInfo);
        if (DisplayInfo.getColumnModel().getColumnCount() > 0) {
            DisplayInfo.getColumnModel().getColumn(0).setResizable(false);
            DisplayInfo.getColumnModel().getColumn(1).setMinWidth(120);
            DisplayInfo.getColumnModel().getColumn(1).setPreferredWidth(120);
            DisplayInfo.getColumnModel().getColumn(1).setMaxWidth(120);
            DisplayInfo.getColumnModel().getColumn(2).setMinWidth(120);
            DisplayInfo.getColumnModel().getColumn(2).setPreferredWidth(120);
            DisplayInfo.getColumnModel().getColumn(2).setMaxWidth(120);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 239, 667, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel2.setText("Total:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 670, 50, 40));

        txtTotalDebit.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtTotalDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalDebitActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 672, 121, -1));

        txtTotalCredit.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jPanel1.add(txtTotalCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 672, 121, -1));

        btnDone.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        jPanel1.add(btnDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 718, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalDebitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalDebitActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UnadjustedTB().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DisplayInfo;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCompany_Name;
    private javax.swing.JTextField txtTotalCredit;
    private javax.swing.JTextField txtTotalDebit;
    // End of variables declaration//GEN-END:variables
}
